name: time_track_management
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  firebase_core: ^2.8.0
  firebase_auth: ^4.8.0
  firebase_database: ^10.5.7
  csv: ^5.0.0
  path_provider: ^2.0.11
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/flowimage.jpg
